# Generated by Django 5.2.5 on 2025-08-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="NICMAH",
                        help_text="Name of the business/site",
                        max_length=100,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Farmers focused business specializing in livestock farming and crop farming for over two decades.",
                        max_length=200,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "business_description",
                    models.TextField(
                        blank=True,
                        default="NICMAH is a farmers focused business that majors on livestock farming and crop farming for over two decades. We provide comprehensive agricultural solutions including AI services, quality seeds, and expert farming guidance.",
                        help_text="Detailed business description and history",
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(
                        blank=True,
                        default="Our mission is to ensure quality, hardy and resistant herds are maintained and passed on through breeding.",
                        help_text="Company mission statement",
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        blank=True,
                        default="Our goal is to help farmers achieve their goals and educating them to ensure their prosperity.",
                        help_text="Company vision statement",
                    ),
                ),
                (
                    "livestock_services",
                    models.TextField(
                        blank=True,
                        default="• AI (Artificial Insemination) services\n• Best livestock breeding practices\n• Quality semen from local and international bulls\n• Livestock health management\n• Breeding consultation and support",
                        help_text="Livestock farming services offered",
                    ),
                ),
                (
                    "crop_services",
                    models.TextField(
                        blank=True,
                        default="• Quality seeds\n• Foliar applications\n• Pest control products\n• Crop management solutions\n• Maximum yield optimization\n• Soil health management",
                        help_text="Crop farming services offered",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="nicmahagrovet@gmail.com", max_length=254
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="0726476128/0740368581",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="Naromoru town, Timberland building near KFA",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, default="https://facebook.com/NicmahAgrovet"
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(blank=True, default="https://tiktok.com/@Nicmah"),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "business_hours",
                    models.TextField(
                        blank=True,
                        default="Monday - Friday: 8:00 AM - 6:00 PM\nSaturday: 8:00 AM - 4:00 PM\nSunday: Closed",
                        help_text="Business operating hours",
                    ),
                ),
                (
                    "years_in_business",
                    models.PositiveIntegerField(
                        default=20, help_text="Number of years in business"
                    ),
                ),
                (
                    "cattle_ai_count",
                    models.PositiveIntegerField(
                        default=1000, help_text="Number of cattle served through AI"
                    ),
                ),
                (
                    "farmers_served",
                    models.PositiveIntegerField(
                        default=1000, help_text="Number of farmers served"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
