# Generated by Django 5.2.5 on 2025-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="veterinary_phone",
            field=models.CharField(
                blank=True,
                default="0721908023",
                help_text="Veterinary services phone number",
                max_length=20,
            ),
        ),
    ]
