# Generated by Django 5.2.5 on 2026-01-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_veterinary_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="254726476128",
                help_text="WhatsApp number in international format (without +)",
                max_length=20,
            ),
        ),
    ]
