# Generated by Django 3.2.25 on 2026-01-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_print_receipts',
            field=models.BooleanField(default=False, help_text='Automatically print receipts after completing a sale'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_baudrate',
            field=models.IntegerField(default=9600, help_text='Serial printer baudrate'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_enabled',
            field=models.BooleanField(default=False, help_text='Enable receipt printing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_host',
            field=models.CharField(blank=True, help_text='Network printer IP address or hostname', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_name',
            field=models.CharField(blank=True, help_text='Printer name (for system printers) or device path/name', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_port',
            field=models.IntegerField(default=9100, help_text='Network printer port (default: 9100 for raw printing)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_serial_port',
            field=models.CharField(blank=True, help_text='Serial port (e.g., COM1 on Windows, /dev/ttyUSB0 on Linux)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='printer_type',
            field=models.CharField(choices=[('system', 'System/USB Printer'), ('serial', 'Serial/COM Port'), ('network', 'Network Printer')], default='system', help_text='Type of receipt printer connection', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='254740368581', help_text='WhatsApp number in international format (without +)', max_length=20),
        ),
    ]
