# Generated by Django 5.2.5 on 2025-08-29 14:00

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("days_since_first_order", models.PositiveIntegerField(default=0)),
                ("days_since_last_order", models.PositiveIntegerField(default=0)),
                (
                    "order_frequency",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Orders per month",
                        max_digits=8,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("new", "New Customer"),
                            ("regular", "Regular Customer"),
                            ("loyal", "Loyal Customer"),
                            ("vip", "VIP Customer"),
                            ("at_risk", "At Risk"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("preferred_categories", models.JSONField(blank=True, default=list)),
                (
                    "preferred_payment_method",
                    models.CharField(blank=True, max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "customer insight",
                "verbose_name_plural": "customer insights",
                "ordering": ["-period_end", "-total_spent"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "Metric Display"),
                            ("chart", "Chart/Graph"),
                            ("table", "Data Table"),
                            ("list", "List View"),
                            ("progress", "Progress Bar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1x1)"),
                            ("medium", "Medium (2x1)"),
                            ("large", "Large (2x2)"),
                            ("full", "Full Width (3x1)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Widget configuration data"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                (
                    "visible_to_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of user roles that can see this widget",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "dashboard widget",
                "verbose_name_plural": "dashboard widgets",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("units_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("starting_stock", models.PositiveIntegerField(default=0)),
                ("ending_stock", models.PositiveIntegerField(default=0)),
                (
                    "stock_turnover",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Profit margin percentage",
                        max_digits=5,
                    ),
                ),
                ("ranking", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "product performance",
                "verbose_name_plural": "product performances",
                "ordering": ["-period_end", "-revenue_generated"],
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("inventory", "Inventory Report"),
                            ("customer", "Customer Report"),
                            ("product", "Product Performance"),
                            ("comprehensive", "Comprehensive Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("report_data", models.JSONField(default=dict)),
                ("summary_data", models.JSONField(default=dict)),
                ("exported_as_pdf", models.BooleanField(default=False)),
                ("exported_as_excel", models.BooleanField(default=False)),
                (
                    "export_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
            ],
            options={
                "verbose_name": "sales report",
                "verbose_name_plural": "sales reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
