# Generated by Django 5.2.5 on 2025-08-29 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinsight",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["widget_type"], name="analytics_d_widget__210862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["is_active"], name="analytics_d_is_acti_2285af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(fields=["order"], name="analytics_d_order_5be5b8_idx"),
        ),
        migrations.AddField(
            model_name="productperformance",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_metrics",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customerinsight",
            index=models.Index(
                fields=["customer"], name="analytics_c_custome_fb032d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerinsight",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="analytics_c_period__d6b5dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerinsight",
            index=models.Index(
                fields=["segment"], name="analytics_c_segment_0f1e0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerinsight",
            index=models.Index(
                fields=["total_spent"], name="analytics_c_total_s_1201a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerinsight",
            unique_together={("customer", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="productperformance",
            index=models.Index(
                fields=["product"], name="analytics_p_product_6224c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productperformance",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="analytics_p_period__1acc87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productperformance",
            index=models.Index(
                fields=["revenue_generated"], name="analytics_p_revenue_0005eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productperformance",
            index=models.Index(
                fields=["ranking"], name="analytics_p_ranking_d0758e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productperformance",
            unique_together={("product", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["report_id"], name="analytics_s_report__8952fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["report_type"], name="analytics_s_report__c3cbdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(fields=["period"], name="analytics_s_period_f79391_idx"),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["start_date", "end_date"], name="analytics_s_start_d_f9aabf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["generated_at"], name="analytics_s_generat_914ff0_idx"
            ),
        ),
    ]
