# Generated by Django 3.2.25 on 2026-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sales_salesanalytics_salesitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesanalytics',
            name='top_products',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of top products'),
        ),
    ]
