# Generated by Django 5.2.5 on 2025-08-29 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_alerts",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="inventory.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_id"], name="inventory_i_transac_c58122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["product"], name="inventory_i_product_70d2e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_type"], name="inventory_i_transac_2eccee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["created_at"], name="inventory_i_created_670884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["alert_id"], name="inventory_s_alert_i_908cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["product"], name="inventory_s_product_de2b11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["alert_type"], name="inventory_s_alert_t_af1483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(fields=["status"], name="inventory_s_status_95e312_idx"),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["priority"], name="inventory_s_priorit_56e803_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["created_at"], name="inventory_s_created_671808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_id"], name="inventory_s_movemen_30f0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product"], name="inventory_s_product_cbdc37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_s_movemen_018f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["created_at"], name="inventory_s_created_05ebf5_idx"
            ),
        ),
    ]
