# Generated by Django 3.2.25 on 2026-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_documenttemplate_document_documentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tags',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of tags'),
        ),
    ]
