# Generated by Django 5.2.5 on 2025-08-29 14:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                            ("buy_one_get_one", "Buy One Get One"),
                            ("bulk_discount", "Bulk Discount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "percentage_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed discount amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum purchase amount to qualify",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "minimum_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum quantity to qualify", null=True
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this discount can be used",
                        null=True,
                    ),
                ),
                ("current_uses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("local_transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("refund", "Refund"),
                            ("void", "Void"),
                        ],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "items_data",
                    models.JSONField(
                        help_text="Stored items data for offline transactions"
                    ),
                ),
                ("payment_method", models.CharField(default="cash", max_length=20)),
                ("payment_status", models.CharField(default="paid", max_length=20)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_offline_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Sync"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Sync Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sync_attempts", models.PositiveIntegerField(default=0)),
                ("last_sync_attempt", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("app_version", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Offline Transaction",
                "verbose_name_plural": "Offline Transactions",
                "ordering": ["-created_offline_at"],
            },
        ),
        migrations.CreateModel(
            name="POSSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "item_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "item_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "POS Sale Item",
                "verbose_name_plural": "POS Sale Items",
            },
        ),
        migrations.CreateModel(
            name="POSSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("suspended", "Suspended"),
                            ("offline", "Offline"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "closing_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                (
                    "total_tax_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_discounts_given",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_cash_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_card_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_mobile_money_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_offline", models.BooleanField(default=False)),
                ("offline_start_time", models.DateTimeField(blank=True, null=True)),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending Sync"),
                            ("failed", "Sync Failed"),
                            ("offline", "Offline Mode"),
                        ],
                        default="synced",
                        max_length=20,
                    ),
                ),
                ("local_transactions", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "POS Session",
                "verbose_name_plural": "POS Sessions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Receipt"),
                            ("duplicate", "Duplicate Receipt"),
                            ("refund", "Refund Receipt"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        help_text="Product barcode (EAN-13, UPC, etc.)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("ean13", "EAN-13"),
                            ("upc", "UPC"),
                            ("code128", "Code 128"),
                            ("qr", "QR Code"),
                            ("custom", "Custom"),
                        ],
                        default="ean13",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barcode",
                "verbose_name_plural": "Barcodes",
                "ordering": ["barcode"],
            },
        ),
        migrations.CreateModel(
            name="POSSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("offline", "Offline"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("offline", "Offline Payment"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "change_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "receipt_number",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_offline_sale", models.BooleanField(default=False)),
                (
                    "offline_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending Sync"),
                            ("failed", "Sync Failed"),
                        ],
                        default="synced",
                        max_length=20,
                    ),
                ),
                (
                    "applied_discounts",
                    models.ManyToManyField(
                        blank=True, related_name="applied_sales", to="pos.discount"
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Sale",
                "verbose_name_plural": "POS Sales",
                "ordering": ["-created_at"],
            },
        ),
    ]
