# Generated by Django 5.2.5 on 2025-08-29 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="possale",
            name="cashier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pos_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="applied_discounts",
            field=models.ManyToManyField(
                blank=True, related_name="applied_items", to="pos.discount"
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pos.possale",
            ),
        ),
        migrations.AddField(
            model_name="possession",
            name="cashier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pos_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="possession",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="pos.possession",
            ),
        ),
        migrations.AddField(
            model_name="offlinetransaction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offline_transactions",
                to="pos.possession",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="sale",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="pos.possale",
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.taxrate",
            ),
        ),
    ]
