# Generated by Django 5.2.5 on 2025-09-03 12:14

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possession",
            name="session_id",
            field=models.CharField(
                default=pos.models.generate_session_id, max_length=20, unique=True
            ),
        ),
    ]
