# Generated by Django 3.2.25 on 2026-01-08 15:17

from django.db import migrations, models


def convert_schema_manually(apps, schema_editor):
    """Manually convert JSONField columns to TEXT using raw SQL."""
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # SQLite stores JSONField as TEXT anyway, so we just need to ensure
        # the schema reflects TEXT type. Since SQLite doesn't enforce types,
        # we can skip this if the data is already stored as TEXT.
        # The AlterField operation will handle the schema change.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20260108_1714'),
    ]

    operations = [
        # Use RunSQL to manually alter the table schema, bypassing Django's validation
        migrations.RunSQL(
            # Forward: SQLite stores JSONField as TEXT anyway, so no change needed
            sql="",
            reverse_sql="",
        ),
        # Change field definitions in Django's state (database already compatible)
        migrations.AlterField(
            model_name='offlinetransaction',
            name='device_info',
            field=models.TextField(blank=True, default='{}', help_text='Device metadata (JSON)'),
        ),
        migrations.AlterField(
            model_name='offlinetransaction',
            name='items_data',
            field=models.TextField(help_text='Stored items data for offline transactions (JSON)'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='local_transactions',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of offline transactions'),
        ),
    ]
