# Generated by Django 5.2.5 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_size",
            field=models.CharField(
                blank=True, help_text="e.g. 100 ml, 180 ml, 1 L, 500 g", max_length=50
            ),
        ),
    ]
