# Generated by Django 5.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_package_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_admin_only",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this category will only be visible to admin users."
            ),
        ),
    ]

