# Generated by Django 3.2.25 on 2026-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_category_parent_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of additional image URLs'),
        ),
    ]
