# Generated by Django 5.2.5 on 2025-09-01 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_order_n_f3ada5_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_59b6fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_c6dd84_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_0e92de_idx",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="created_at",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="delivery_notes",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer_address",
            new_name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipped_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="source",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="whatsapp_conversation_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="whatsapp_message_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_sku",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
